#!/bin/bash
set -o pipefail
test=strexpander
${PBP}/output_begin
cat ${test}.grid |\
    ${PBP}/t2t strexpander |\
    fanout 2> >(${PBP}/output_to_port "0.grid") |\
           ${PBP}/t2t pythonize | ${PBP}/output_to_port "py"
${PBP}/output_end
${PBP}/splitoutputs <out.json

